name: realtime_database_ogabekdev
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.1.0
  pinput: ^2.2.12
  flutter_svg: ^1.1.5
  firebase_core: ^2.1.0
  firebase_database: ^10.0.2
  firebase_auth: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

